{{- if .Values.quota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota
  namespace: {{ include "tenant-onboarding.namespace" . }}
spec:
  hard:
{{ toYaml .Values.quota.hard | indent 4 }}
{{- end }}
